# ²âÊÔ»·¾³ÅäÖÃ

# Â·ÓÉÆ÷ÅäÖÃ
router:
  ip: 192.168.31.102
  login_path: "/cgi-bin/luci/api/xqsystem/login"

# ²âÊÔÕËºÅ
test_account:
  valid:
    password: "13027106711"
  invalid:
    password: "wrong123"